#!/bin/bash

#Ascii color variables
r="\033[1;31m"
b="\e[1m"
n="\e[0m"

# Is adb installed?
[ -z $(which adb) ] && echo "Please install adb!" && exit 1

# Defining Variables
LOKASI=~/android-debloater/1.apk
app="$2"
berhasil="Success"

help() {
     echo -e "${b}ANDROID DEBLOATER CLI SCRIPT${n}"
     echo -e "Semi-automated, make your work easier\n"
     echo -e "${b}OPTIONS:${n} \nFind app to Uninstall:\t\tfind [APP-NAME]"
     echo -e "Uninstall an app:\t\tremove [APP-PACKAGE-NAME]"
     echo -e "Install Helper to your phone:\tinstall-helper\n"
     echo -e "${r}TO RESTORE, YOU NEED TO DO A FACTORY RESET"
     echo -e "SO DO THIS CAREFULLY OR YOUR PHONE WILL BE BROKEN!!${n}"
}

arg_err() {
     echo -e "${b}Wrong arguments!${n}"
     echo -e "See ${r}android-debloater help${n} for some helps"
}

ins_help() {
     adb install $LOKASI && exit
}

find() {
     adb shell pm list packages | grep ${app} | cut -c 9-
}

# In case of NO Argument
[ -z $1 ] && help | head -n1 -n2 && echo -e "\nsee ${r}android-debloater help${n} for helps" && exit

# Executing Command
case $1 in
     remove)
          if [[ $(adb shell pm uninstall $2) = $berhasil ]]; then
               echo "Success"
          else
               adb shell pm uninstall -k --user 0 $2
          fi
          exit
          ;;
     help)
          help
          ;;
     find)
          echo "----" 
          printf "%b$(find)%b\n" "$r" "$n"
          echo "----" 
          exit
          ;;
     install-helper)
          ins_help
          exit
          ;;
     *)
          arg_err
          exit
          ;;
esac
